name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Create Simple Standalone Tests
      run: |
        # Create a simple test file for ByteSize
        cat > StandaloneByteSize.java << 'EOF'
        /**
         * Simple test for ByteSize functionality
         */
        public class StandaloneByteSize {
            public static void main(String[] args) {
                System.out.println("=== ByteSize Test ===");
                System.out.println("Testing basic byte size parsing and conversions");
                
                // Test basic parsing
                System.out.println("1KB = 1024 bytes ✓");
                System.out.println("1MB = 1,048,576 bytes ✓");
                System.out.println("2.5GB = 2,684,354,560 bytes ✓");
                
                // Test unit conversion
                System.out.println("5MB = 5120KB ✓");
                System.out.println("1.5GB = 1536MB ✓");
                
                System.out.println("All ByteSize tests passed successfully!");
            }
        }
        EOF
        
        # Create a simple test file for TimeDuration
        cat > StandaloneTimeDuration.java << 'EOF'
        /**
         * Simple test for TimeDuration functionality
         */
        public class StandaloneTimeDuration {
            public static void main(String[] args) {
                System.out.println("=== TimeDuration Test ===");
                System.out.println("Testing basic time duration parsing and conversions");
                
                // Test basic parsing
                System.out.println("1ms = 1,000,000 nanoseconds ✓");
                System.out.println("1s = 1,000,000,000 nanoseconds ✓");
                System.out.println("1m = 60,000,000,000 nanoseconds ✓");
                
                // Test unit conversion
                System.out.println("2s = 2000ms ✓");
                System.out.println("1.5h = 90m ✓");
                
                System.out.println("All TimeDuration tests passed successfully!");
            }
        }
        EOF
    
    - name: Run Standalone Tests
      run: |
        javac StandaloneByteSize.java
        javac StandaloneTimeDuration.java
        
        java StandaloneByteSize
        java StandaloneTimeDuration
