name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Clean and Prepare
      run: |
        # Remove any pre-compiled class files
        find . -name "*.class" -type f -delete
        # Create output directories
        mkdir -p target/classes/io/cdap/wrangler/api/parser
    
    - name: Compile Core Classes
      run: |
        # Compile core interfaces and classes first
        javac -d target/classes wrangler-api/src/main/java/io/cdap/wrangler/api/parser/TokenType.java
        javac -d target/classes wrangler-api/src/main/java/io/cdap/wrangler/api/parser/Token.java
        javac -d target/classes wrangler-api/src/main/java/io/cdap/wrangler/api/parser/SyntaxError.java
        javac -d target/classes -cp target/classes wrangler-api/src/main/java/io/cdap/wrangler/api/parser/ByteSize.java
        javac -d target/classes -cp target/classes wrangler-api/src/main/java/io/cdap/wrangler/api/parser/TimeDuration.java
    
    - name: Compile and Run Tests
      run: |
        # Compile test classes
        javac -cp .:target/classes ByteSizeTest.java
        javac -cp .:target/classes TimeDurationTest.java
        
        # Run tests
        java -cp .:target/classes ByteSizeTest
        java -cp .:target/classes TimeDurationTest
